name: tezz_cafe
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.4 <4.0.0'

dependencies:
  awesome_extensions: ^2.0.12
  dartz: ^0.10.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  gap: ^3.0.1
  get_it: ^7.6.7
  shared_preferences: ^2.2.2
  mask_text_input_formatter: ^2.8.0
  flutter_lints: ^3.0.1
  cached_network_image: ^3.3.1
  path_provider: ^2.1.2
  flutter_svg: ^2.0.9
  freezed_annotation: ^2.4.1
  loading_animation_widget: ^1.2.0+4
  json_annotation: ^4.8.1
  retrofit: ^4.0.3
  dio: ^5.4.0
  formz: ^0.6.1
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  retrofit_generator: ^8.0.6
  build_runner: ^2.4.8
  json_serializable: ^6.7.1
  freezed: ^2.4.6


flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
