name: tezz_cafe
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_svg: ^1.1.6
  mask_text_input_formatter: ^2.8.0
  gap: ^3.0.1
  flutter_bloc: ^8.1.3
  cached_network_image: ^3.3.1
  path_provider: ^2.0.11

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/