name: tezz_cafe
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.4 <4.0.0'

dependencies:
  awesome_extensions: ^2.0.12
  dartz: ^0.10.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_svg: ^2.0.9
  gap: ^3.0.1
  get_it: ^7.6.7
  shared_preferences: ^2.2.2
  mask_text_input_formatter: ^2.8.0
  flutter_lints: ^3.0.1
  cached_network_image: ^3.3.1
  path_provider: ^2.1.2


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
